import type { FieldType } from "@/types";

export const mockData: Partial<FieldType>[] = [
  {
    type: "titulo_subtitulo",
    dsTitulo: "Dados do Segurado",
    dsSubtitulo: "Informe os dados pessoais do segurado",
    sessao: "001",
  },
  {
    campoApi: "nome_segurado",
    nome: "Nome completo dos Segurados",
    placeholder: "Digite o nome completo do Segurado",
    obrigatorio: true,
    conteudo: "Itamar Soares",
    type: "textarea",
    campoCompartilhado: false,
    qtdRespostas: 3,
    sessao: "001",
  },
  {
    type: "tabela",
    campoApi: "multiplas_respostas_tabela",
    nome: "Localização das lojas",
    placeholder: "Preencha as informações",
    obrigatorio: true,
    colunas: [
      {
        type: "text",
        nome: "Nome da loja",
        placeholder: "Digite o nome da loja",
        obrigatorio: true,
        conteudo: "",
        id: "2e626834-5b0b-4978-b877-69436c4d5917",
      },
      {
        type: "text",
        nome: "Cidade",
        placeholder: "Digite a cidade",
        obrigatorio: true,
        conteudo: "",
        id: "d8dfcb94-5a1e-4cc0-9996-998ba7d2f122",
      },
      {
        type: "text",
        nome: "Estado",
        placeholder: "Digite o estado",
        obrigatorio: true,
        conteudo: "",
        id: "fe995257-3762-4313-a90f-82dc646ebd10",
      },
      {
        type: "text",
        nome: "CEP",
        placeholder: "Digite o CEP",
        obrigatorio: true,
        conteudo: "",
        mask: "cep",
        id: "f962a480-7b76-4f43-b02e-d7634e7ce510",
      },
      {
        type: "text",
        nome: "Bairro",
        placeholder: "Digite o bairro",
        obrigatorio: true,
        conteudo: "",
        id: "4bb887e8-fc47-42be-8222-e0c0867c5bd4",
      },
      {
        type: "text",
        nome: "Logradouro",
        placeholder: "Digite o logradouro",
        obrigatorio: true,
        conteudo: "",
        id: "f32d5ac6-2cb2-4526-a0e4-1c70b8314616",
      },
    ],
    conteudo: '',
    sessao: "001",
  },
  {
    campoApi: "campo_combo_checkbox",
    nome: "Combo de opções",
    obrigatorio: true,
    type: "combo_checkbox",
    options: "Opção 1:1;Opção 2:2;Opção 3:3;",
    campoCompartilhado: false,
    qtdRespostas: 3,
    placeholder: "Selecione as opções",
    sessao: "001",
  },
  {
    campoApi: "checkbox",
    nome: "deseja receber notificações?",
    obrigatorio: true,
    type: "checkbox",
    campoCompartilhado: false,
    sessao: "001",
  },
  {
    campoApi: "telefone_segurado",
    nome: "telefone do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "telefone",
    sessao: "001",
  },
  {
    campoApi: "email_segurado",
    nome: "Email do Segurado",
    obrigatorio: false,
    type: "email",
    campoCompartilhado: false,
    qtdRespostas: 99,
    placeholder: "Responda com o email do Segurado",
    sessao: "001",
  },
  {
    campoApi: "cep_segurado",
    nome: "cep do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "cep",
    sessao: "001",
  },
  {
    campoApi: "cnpj_segurado",
    nome: "cnpj do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "cnpj",
    sessao: "001",
  },
  {
    campoApi: "rg_segurado",
    nome: "rg do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "rg",
    sessao: "001",
  },
  {
    campoApi: "data_nascimento",
    nome: "Data de nascimento",
    obrigatorio: false,
    type: "date",
    campoCompartilhado: false,
    sessao: "001",
    dateConfig: "maxToday",
  },
  {
    campoApi: "estado_civil",
    nome: "Estado civil",
    obrigatorio: false,
    type: "select",
    options: "Solteiro:1;Casado:2;Divorciado:3;Viúvo:4;",
    campoCompartilhado: false,
    qtdRespostas: 99,
    placeholder: "Selecione as opções",
    sessao: "001",
  },
  // {
  //   type: "titulo_subtitulo",
  //   dsTitulo: "Informações do Veículo",
  //   dsSubtitulo: "Informe os dados referentes ao carro segurado",
  //   sessao: "002",
  // },
  // {
  //   campoApi: "placa_veiculo",
  //   nome: "Placa do veículo",
  //   obrigatorio: false,
  //   type: "text",
  //   campoCompartilhado: false,
  //   sessao: "002",
  // },
  // {
  //   campoApi: "marca_modelo",
  //   nome: "Marca e Modelo",
  //   obrigatorio: false,
  //   type: "text",
  //   campoCompartilhado: false,
  //   sessao: "002",
  // },
  // {
  //   campoApi: "ano_fabricacao",
  //   nome: "Ano de fabricação",
  //   obrigatorio: false,
  //   type: "number",
  //   campoCompartilhado: false,
  //   qtdRespostas: 99,
  //   placeholder: "Preencha com o ano de fabricação",
  //   sessao: "002",
  // },
  // {
  //   campoApi: "uso_veiculo",
  //   nome: "Uso do veículo",
  //   obrigatorio: false,
  //   type: "select",
  //   options: "Particular:1;Comercial:2;Aplicativo:3;",
  //   campoCompartilhado: false,
  //   sessao: "002",
  // },
  // {
  //   campoApi: "valor_veiculo",
  //   nome: "Valor do veículo (BRL)",
  //   obrigatorio: false,
  //   type: "text",
  //   mask: "BRL",
  //   campoCompartilhado: false,
  //   sessao: "002",
  // },
  // {
  //   campoApi: "calculo_total_veicoulo",
  //   nome: "Valor Total do Seguro (BRL)",
  //   obrigatorio: false,
  //   type: "calculado",
  //   calculo: "({{valor_veiculo}} * {{ano_fabricacao}}) / 2",
  //   campoCompartilhado: false,
  //   sessao: "002",
  //   mask: "BRL",
  // },
];