import type { FieldType } from "@/types";

export const mockData: Partial<FieldType>[] = [
  {
    type: "titulo_subtitulo",
    dsTitulo: "Dados do Segurado",
    dsSubtitulo: "Informe os dados pessoais do segurado",
    sessao: "001",
  },
  {
    campoApi: "nome_segurado",
    nome: "Nome completo do Segurado",
    obrigatorio: true,
    conteudo: "Itamar Soares",
    type: "textarea",
    campoCompartilhado: false,
    sessao: "001",
  },
  {
    campoApi: "campo_combo_checkbox",
    nome: "Combo de opções",
    obrigatorio: true,
    type: "combo_checkbox",
    options: "Opção 1:1;Opção 2:2;Opção 3:3;",
    campoCompartilhado: false,
    sessao: "001",
  },
  {
    campoApi: "telefone_segurado",
    nome: "telefone do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "telefone",
    sessao: "001",
  },
  {
    campoApi: "cep_segurado",
    nome: "cep do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "cep",
    sessao: "001",
  },
  {
    campoApi: "cnpj_segurado",
    nome: "cnpj do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "cnpj",
    sessao: "001",
  },
  {
    campoApi: "rg_segurado",
    nome: "rg do Segurado",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    mask: "rg",
    sessao: "001",
  },
  {
    campoApi: "data_nascimento",
    nome: "Data de nascimento",
    obrigatorio: false,
    type: "date",
    campoCompartilhado: false,
    sessao: "001",
    dateConfig: "maxToday",
  },
  {
    campoApi: "estado_civil",
    nome: "Estado civil",
    obrigatorio: false,
    type: "select",
    options: "Solteiro:1;Casado:2;Divorciado:3;Viúvo:4;",
    campoCompartilhado: false,
    sessao: "001",
  },
  {
    type: "titulo_subtitulo",
    dsTitulo: "Informações do Veículo",
    dsSubtitulo: "Informe os dados referentes ao carro segurado",
    sessao: "002",
  },
  {
    campoApi: "placa_veiculo",
    nome: "Placa do veículo",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    sessao: "002",
  },
  {
    campoApi: "marca_modelo",
    nome: "Marca e Modelo",
    obrigatorio: false,
    type: "text",
    campoCompartilhado: false,
    sessao: "002",
  },
  {
    campoApi: "ano_fabricacao",
    nome: "Ano de fabricação",
    obrigatorio: false,
    type: "number",
    campoCompartilhado: false,
    sessao: "002",
  },
  {
    campoApi: "uso_veiculo",
    nome: "Uso do veículo",
    obrigatorio: false,
    type: "select",
    options: "Particular:1;Comercial:2;Aplicativo:3;",
    campoCompartilhado: false,
    sessao: "002",
  },
  {
    campoApi: "valor_veiculo",
    nome: "Valor do veículo (BRL)",
    obrigatorio: false,
    type: "text",
    mask: "BRL",
    campoCompartilhado: false,
    sessao: "002",
  },
  {
    campoApi: "calculo_total_veicoulo",
    nome: "Valor Total do Seguro (BRL)",
    obrigatorio: false,
    type: "calculado",
    calculo: "({{valor_veiculo}} * {{ano_fabricacao}}) / 2",
    campoCompartilhado: false,
    sessao: "002",
    mask: "BRL",
  },
];
